import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AuthView {
    in property <string> button_text;
    in property <string> placeholder_text;
    in property <bool> is_error: false;
    in property <string> error_msg: "";

    in-out property <string> passfield: "";
    callback submitted(string);

    VerticalLayout {
        alignment: center;
        padding-top: 50px;
        spacing: 100px;
        Text {
            text: "Rust Password Manager";
            font-size: 36px;
            color: Colors.darkorange;
            horizontal-alignment: center;
        }

        GridLayout {
            spacing: 50px;
            padding: 25px;
            Row {
                HorizontalLayout {
                    alignment: center;
                    LineEdit {
                        min-width: 400px;
                        min-height: 50px;
                        text <=> root.passfield;
                        input-type: InputType.password;
                        placeholder-text: root.placeholder_text;
                        accepted(text) => {
                            root.submitted(root.passfield);
                        }
                    }
                }
            }

            Row {
                HorizontalLayout {
                    alignment: center;
                    Button {
                        min-width: 125px;
                        primary: true;
                        text: root.button_text;
                        clicked => {
                            root.submitted(root.passfield);
                        }
                    }
                }
            }

            Row {
                HorizontalLayout{
                    alignment: center;
                    Text {
                        font-size: 18px;
                        text: root.error_msg;
                        color: #ff5555;
                        visible: root.is_error;
                    }
                }
            }
        }
    }
}
