import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component CreateDbWindow inherits Window {
    height: 720px;
    width: 1280px;


    property <string> passfield: "";
    callback createdb(string); // Define a signal that carries a string


    VerticalLayout {
        alignment: center;
        padding-top: 50px;
        spacing: 100px;
        Text {
            text: "Rust Password Manager";
            font-size: 36px;
            color: Colors.darkorange;
            horizontal-alignment: center;
        }

        GridLayout {
            spacing: 50px;
            padding: 25px;
            width: root.width;
            height: root.height;
            Row{
                HorizontalLayout {
                    alignment: center;
                    LineEdit {
                        width: root.width * 50%;
                        height: 75px;
                        text <=> root.passfield;
                        input-type: InputType.password;
                        placeholder-text: "Root Salt";
                        accepted(text) => {
                            createdb(root.passfield);
                        }
                    }
                }
            }

            Row{
                HorizontalLayout {
                alignment: center;
                    Button {
                        height: root.height * 5%;
                        width: root.width * 20%;
                        primary: true;
                        text: "Create DB";
                        clicked => {
                            createdb(root.passfield);
                        }
                    }
                }
            }
        }
    }
}
