import { Button } from "std-widgets.slint";
import { AuthView } from "auth-view.slint";
import { ServiceView, AppData, FormMode} from "services-view.slint";
import { ServiceData } from "service-form.slint";
import "./fonts/C059-Roman.otf";

export enum Page {
    CreateDb,
    Authenticate,
    Passlock
}

export { AppData }

export component EntryWindow inherits Window {
    callback create_db_submitted(string);
    callback authenticate_submitted(string);
    callback generate_password()->string;
    callback save_service(ServiceData, string, int);
    callback delete_entry(string);
    callback copy_to_clipboard(string, string);

    title: "PassLock";
    min-width: 1280px;
    min-height: 720px;
    full-screen: false;
    default-font-size: 16px;
    default-font-family: "C059";
    icon: @image-url("../resources/panda.png");
    in-out property <Page> current_page: Page.CreateDb;
    in-out property <bool> auth-error: false;
    in-out property <int> shake-trigger: 0;

    if current_page == Page.CreateDb: AuthView {
        button_text: "Create Database";
        placeholder_text: "Enter a strong master password";
        submitted(str) => { root.create_db_submitted(str) }
    }
    if current_page == Page.Authenticate: auth-view := AuthView {
        button_text: "Authenticate";
        placeholder_text: "Enter your master password";
        show-error <=> root.auth-error;
        shake-state: root.shake-trigger;
        submitted(str) => { root.authenticate_submitted(str) }
    }
    if current_page == Page.Passlock:  ServiceView{
        generate_password() => { root.generate_password() }
        save_service(data, mode, row) => { root.save_service(data, mode, row) }
        delete_entry(id) => { root.delete_entry(id) }
        copy_to_clipboard(value, field_name) => { root.copy_to_clipboard(value, field_name) }
    }
}