import { Button } from "std-widgets.slint";
import { AuthView } from "auth-view.slint";
import {ServiceView} from "services-view.slint";

export enum Page {
    CreateDb,
    Authenticate,
    Passlock
}

export component EntryWindow inherits Window {
    callback create_db_submitted(string);
    callback authenticate_submitted(string);
    callback generate_password()->string;

    title: "PassLock";
    min-width: 1280px;
    min-height: 720px;
    icon: @image-url("../resources/ico.png");

    in-out property <Page> current_page: Page.CreateDb;


    if current_page == Page.CreateDb: AuthView {
        button_text: "Create Database";
        placeholder_text: "Enter a strong master password";
        submitted(str) => { root.create_db_submitted(str) }
    }
    if current_page == Page.Authenticate: AuthView {
        button_text: "Authenticate";
        placeholder_text: "Enter your master password";
        submitted(str) => { root.authenticate_submitted(str) }
    }
    if current_page == Page.Passlock:  ServiceView{
        generate_password() => { root.generate_password() }
    }
}